Stop supporting to write ID3 tags into FLAC files
This is not (anymore?) supported at all by libflac, with e.g.  oggenc
erroring out with:
  ERROR: Input file "song.flac" is not a supported format

Even as an option it does more harm than good due to people accidentally
enabling it.

FLAC pictures are supported since EasyTAG 2.1.4. Fixes bug 700724.